/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BestSellingWidget: typeof import('./src/components/dashboard/BestSellingWidget.vue')['default']
    BomDetailWidget: typeof import('./src/components/information/bom/bomDetailWidget.vue')['default']
    BomListWidget: typeof import('./src/components/information/bom/bomListWidget.vue')['default']
    BomRegisterWidget: typeof import('./src/components/information/bom/bomRegisterWidget.vue')['default']
    BomSearchWidget: typeof import('./src/components/information/bom/bomSearchWidget.vue')['default']
    Button: typeof import('primevue/button')['default']
    Chart: typeof import('primevue/chart')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    EmployeeListWidget: typeof import('./src/components/information/employee/employeeListWidget.vue')['default']
    EmployeeRegistWidget: typeof import('./src/components/information/employee/employeeRegistWidget.vue')['default']
    EmployeeSearchWidget: typeof import('./src/components/information/employee/employeeSearchWidget.vue')['default']
    FeaturesWidget: typeof import('./src/components/landing/FeaturesWidget.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    FooterWidget: typeof import('./src/components/landing/FooterWidget.vue')['default']
    HeroWidget: typeof import('./src/components/landing/HeroWidget.vue')['default']
    HighlightsWidget: typeof import('./src/components/landing/HighlightsWidget.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    NotificationsWidget: typeof import('./src/components/dashboard/NotificationsWidget.vue')['default']
    OrderRegisList: typeof import('./src/components/sales/orderRegist/orderRegisList.vue')['default']
    OrderRegistSearch: typeof import('./src/components/sales/orderRegist/orderRegistSearch.vue')['default']
    PricingWidget: typeof import('./src/components/landing/PricingWidget.vue')['default']
    RecentSalesWidget: typeof import('./src/components/dashboard/RecentSalesWidget.vue')['default']
    RevenueStreamWidget: typeof import('./src/components/dashboard/RevenueStreamWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/common/Search.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    StatsWidget: typeof import('./src/components/dashboard/StatsWidget.vue')['default']
    StockCommButton: typeof import('./src/components/stock/stockCommButton.vue')['default']
    StockCommSearchBox: typeof import('./src/components/stock/stockCommSearchBox.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    TopbarWidget: typeof import('./src/components/landing/TopbarWidget.vue')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
